import React, { useState, useEffect, useMemo } from 'react';
import { MailOpen, Copy, Mail, Sparkles, Calendar, ArrowRight, ExternalLink, Activity } from 'lucide-react';
import Card from '../UI/Card';
import Button from '../UI/Button';
import { jobs } from '../../data/jobs';
import { calculateMatchScore, getScoreColor } from '../../utils/scoring';

const Digest = () => {
    const [digest, setDigest] = useState(null);
    const [preferences, setPreferences] = useState(null);
    const [copyStatus, setCopyStatus] = useState(null);
    const [statusHistory, setStatusHistory] = useState([]);

    const today = new RegExp(/^\d{4}-\d{2}-\d{2}$/).test(new Date().toISOString().split('T')[0])
        ? new Date().toISOString().split('T')[0]
        : '2026-02-13';

    const digestKey = `jobTrackerDigest_${today}`;

    useEffect(() => {
        const prefs = localStorage.getItem('jobTrackerPreferences');
        if (prefs) setPreferences(JSON.parse(prefs));

        const savedDigest = localStorage.getItem(digestKey);
        if (savedDigest) setDigest(JSON.parse(savedDigest));

        const history = JSON.parse(localStorage.getItem('jobTrackerStatusHistory') || '[]');
        setStatusHistory(history);
    }, [digestKey]);

    const generateDigest = () => {
        if (!preferences) return;
        const scoredJobs = jobs.map(job => ({
            ...job,
            matchScore: calculateMatchScore(job, preferences)
        }));
        const topMatches = scoredJobs
            .sort((a, b) => {
                if (b.matchScore !== a.matchScore) return b.matchScore - a.matchScore;
                return a.postedDaysAgo - b.postedDaysAgo;
            })
            .slice(0, 10);
        const newDigest = {
            date: new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' }),
            jobs: topMatches
        };
        setDigest(newDigest);
        localStorage.setItem(digestKey, JSON.stringify(newDigest));
    };

    const getPlainTextDigest = () => {
        if (!digest) return "";
        let text = `Top 10 Jobs For You — 9AM Digest (${digest.date})\n\n`;
        digest.jobs.forEach((job, i) => {
            text += `${i + 1}. ${job.title} | ${job.company}\n`;
            text += `   Match: ${job.matchScore}% | ${job.location} (${job.mode})\n`;
            text += `   Apply: ${job.applyUrl}\n\n`;
        });
        text += "Generated by KodNest Premium Job Notification Tracker.";
        return text;
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(getPlainTextDigest());
        setCopyStatus("Copied to clipboard!");
        setTimeout(() => setCopyStatus(null), 3000);
    };

    const createEmailDraft = () => {
        if (!digest) return;
        const subject = `My 9AM Job Digest - ${digest.date}`;
        const body = getPlainTextDigest().replace(/\n/g, '\r\n');
        const mailtoUrl = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
        const link = document.createElement('a');
        link.href = mailtoUrl;
        document.body.appendChild(link);
        link.click();
        setTimeout(() => document.body.removeChild(link), 100);
    };

    if (!preferences) {
        return (
            <div className="digest-page flex flex-col items-center justify-center text-container">
                <div className="empty-state-icon" style={{ color: 'var(--accent-base)', marginBottom: 'var(--space-2)' }}>
                    <Sparkles size={64} strokeWidth={1} />
                </div>
                <h2 className="serif" style={{ fontSize: '2rem', marginBottom: 'var(--space-1)' }}>Unlock Your Digest.</h2>
                <p className="text-muted" style={{ maxWidth: '400px', textAlign: 'center', marginBottom: 'var(--space-3)' }}>
                    Set your preferences to activate intelligent matching and receive a curated 9AM digest every morning.
                </p>
                <Button onClick={() => window.location.href = '/settings'}>
                    Go to Settings
                </Button>
            </div>
        );
    }

    return (
        <div className="digest-page">
            <div className="digest-header flex justify-between items-end mb-4">
                <div>
                    <h1 className="serif">Daily Digest</h1>
                    <p className="text-muted">Curation of your highest-impact opportunities.</p>
                </div>
                {!digest && (
                    <Button onClick={generateDigest} className="flex items-center gap-2">
                        <MailOpen size={18} /> Generate Today's Digest
                    </Button>
                )}
            </div>

            <div className="digest-layout flex flex-col gap-8">
                {!digest ? (
                    <div className="flex flex-col items-center justify-center py-20 bg-card-mockup">
                        <MailOpen size={48} strokeWidth={1} className="text-muted mb-3" />
                        <h3 className="serif text-muted">Ready for Curation.</h3>
                        <p className="text-muted text-sm">Waiting for 9AM trigger simulation.</p>
                    </div>
                ) : (
                    <div className="digest-container">
                        <div className="digest-newsletter">
                            <div className="newsletter-header border-bottom">
                                <div className="flex justify-between items-start">
                                    <div>
                                        <h2 className="serif">Top 10 Jobs For You — 9AM Digest</h2>
                                        <p className="text-muted flex items-center gap-1 mt-1">
                                            <Calendar size={14} /> {digest.date}
                                        </p>
                                    </div>
                                    <div className="demo-badge">Demo Mode</div>
                                </div>
                            </div>

                            <div className="newsletter-body">
                                {digest.jobs.map((job, idx) => (
                                    <div key={job.id} className="digest-item flex justify-between items-center border-bottom">
                                        <div className="job-info">
                                            <div className="flex items-center gap-2">
                                                <span className="job-rank">{idx + 1}</span>
                                                <h4 className="serif">{job.title}</h4>
                                            </div>
                                            <p className="company-text">{job.company}</p>
                                            <div className="meta-text flex gap-3 mt-1">
                                                <span>{job.location}</span>
                                                <span>{job.experience}</span>
                                            </div>
                                        </div>
                                        <div className="job-action-area flex flex-col items-end gap-2">
                                            <div className="match-indicator" style={{ color: getScoreColor(job.matchScore) }}>
                                                {job.matchScore}% Match
                                            </div>
                                            <a href={job.applyUrl} target="_blank" rel="noopener noreferrer">
                                                <div className="inline-link flex items-center gap-1">
                                                    Apply <ExternalLink size={12} />
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                ))}
                            </div>

                            <div className="newsletter-footer pt-4 border-top">
                                <p className="text-muted" style={{ fontSize: '0.8125rem' }}>
                                    This digest was generated based on your intentional career preferences.
                                </p>
                            </div>
                        </div>

                        <div className="digest-actions flex gap-3 mt-4">
                            <Button variant="secondary" onClick={copyToClipboard} className="flex-1 flex items-center justify-center gap-2">
                                <Copy size={16} /> {copyStatus || "Copy to Clipboard"}
                            </Button>
                            <Button variant="secondary" onClick={createEmailDraft} className="flex-1 flex items-center justify-center gap-2">
                                <Mail size={16} /> Create Email Draft
                            </Button>
                        </div>
                    </div>
                )}

                {/* Recent Status Updates Section */}
                <div className="status-history-section pt-8">
                    <div className="flex items-center gap-2 mb-4">
                        <Activity size={20} className="text-accent" />
                        <h2 className="serif">Recent Status Updates</h2>
                    </div>

                    {statusHistory.length > 0 ? (
                        <div className="history-card bg-white p-4 rounded border">
                            <div className="flex flex-col gap-4">
                                {statusHistory.map((entry, i) => (
                                    <div key={i} className="history-item flex justify-between items-center pb-3 border-bottom last-no-border">
                                        <div>
                                            <h4 className="font-bold" style={{ fontSize: '0.9375rem' }}>{entry.title}</h4>
                                            <p className="text-muted text-xs">{entry.company} • {new Date(entry.timestamp).toLocaleDateString()} {new Date(entry.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</p>
                                        </div>
                                        <div className={`status-pill px-3 py-1 rounded-full text-xs font-bold ${entry.status.toLowerCase().replace(' ', '-')}`}>
                                            {entry.status}
                                        </div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ) : (
                        <div className="empty-history p-10 text-center bg-white rounded border border-dashed">
                            <p className="text-muted text-sm italic">Application status changes will appear here.</p>
                        </div>
                    )}
                </div>
            </div>

            <style jsx>{`
        .digest-page {
          padding: var(--space-4);
          max-width: 800px;
          margin: 0 auto;
          width: 100%;
        }
        .bg-card-mockup {
          background: white;
          border: 1px dashed var(--border-color);
          border-radius: var(--radius);
        }
        .digest-newsletter {
          background: white;
          padding: var(--space-4);
          border: 1px solid var(--border-color);
          border-radius: var(--radius);
          box-shadow: 0 10px 30px rgba(0,0,0,0.02);
        }
        .newsletter-header {
          padding-bottom: var(--space-3);
          margin-bottom: var(--space-3);
        }
        .border-bottom {
          border-bottom: 1px solid var(--border-color);
        }
        .last-no-border:last-of-type { border-bottom: none; }
        .demo-badge {
          font-size: 0.625rem;
          font-weight: 700;
          text-transform: uppercase;
          background: var(--bg-primary);
          padding: 2px 8px;
          border-radius: 12px;
          opacity: 0.5;
        }
        .digest-item { padding: var(--space-3) 0; }
        .digest-item:last-of-type { border-bottom: none; }
        .job-rank {
          font-family: var(--font-serif);
          font-size: 1.25rem;
          color: var(--accent-base);
          opacity: 0.3;
          min-width: 24px;
        }
        .company-text { font-size: 0.875rem; font-weight: 500; opacity: 0.8; margin-left: 32px; }
        .meta-text { font-size: 0.75rem; color: var(--text-primary); opacity: 0.5; margin-left: 32px; }
        .match-indicator { font-size: 0.875rem; font-weight: 700; }
        .inline-link { font-size: 0.8125rem; font-weight: 600; color: var(--accent-base); }
        .status-pill { text-transform: capitalize; }
        .status-pill.applied { background: #EBF5FF; color: #3B82F6; }
        .status-pill.rejected { background: #FEF2F2; color: #EF4444; }
        .status-pill.selected { background: #ECFDF5; color: #10B981; }
        .status-pill.not-applied { background: #F3F4F6; color: #666666; }
        .pt-4 { padding-top: 32px; }
        .pt-8 { padding-top: 64px; }
        .mt-1 { margin-top: 4px; }
        .mt-4 { margin-top: 32px; }
        .py-10 { padding: 40px 0; }
        .py-20 { padding: 80px 0; }
        .mb-3 { margin-bottom: 24px; }
        .mb-4 { margin-bottom: 32px; }
      `}</style>
        </div>
    );
};

export default Digest;
